### ISSUE TITLE
Files missing from project

### ISSUE THREAD

**Issue by howardck** [saniul/UIFocusEngine-Talk-SLUG-December-2015#1]
An attempt to compile the project fails. Interface Builder reports it is unable to find UserInitiatedFocusChange.storyboard, Occlusion.storyboard, and the file navigator shows missing entries for OcculsionViewController.swift and FocusGuidesViewController.swift.

**Comment by saniul** [comment]
Sorry about that, I'll take a look later today

**Comment by howardck** [comment]
Thanks Saniul. I just posted an issue against the repo. (I’ve never done that before, so thanks for the opportunity of learning how :-)
Howard

**Comment by saniul** [comment]
That should've fixed it, let me know if anything else goes wrong

**Comment by howardck** [comment]
Thank you.On Jan 25, 2016, at 10:32 AM, Saniul Ahmed notifications@github.com wrote:That should've fixed it, let me know if anything else goes wrong—Reply to this email directly or view it on GitHub.

**Comment by howardck** [comment]
Just compiled and ran sections 0 and 1. All looks good. I was particularly interested in seeing what you had to do to hand-roll your own focus guides. Yikes! :-) I want to do something similar for a big grid of UIViews I’ve got, but I’m  not even using auto layout (I am a true dinosaur! :-), and I’m not sure which way to go at this point.

Thanks for all that hard work.
Howard
